server:
  port: 8070

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: post-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userprofile
      username: JavaUser
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

rabbitmq:
  exchange: exchange-create-post
  queueCreatePost: queue-create-post
  bindingKeyCreatePost: binding-create-post