server:
  port: 8080
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: userprofile-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userprofile
      username: JavaUser
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

rabbitmq:
  queueRegister: register-queue
  exchange: user-exchange
  queueElasticRegister: elastic-register-queue
  elasticRegisterBindingKey: binding-key
  queueCreatePost: queue-create-post